_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 12
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 12
                - 49
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 256
device:
    value: cuda
distributed:
    value: false
gpu_ids:
    value:
        - 0
learning_rate:
    value: 0.0001
master_addr:
    value: localhost
master_port:
    value: "12358"
num_epochs:
    value: 5
use_wandb:
    value: true
wandb_project:
    value: timesfm-finetuning
weight_decay:
    value: 0.01
